version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: "jenkins.Dockerfile"
    privileged: true
    user: root
    networks:
      - "jenkins-network"
    ports:
      - 8081:8080
    container_name: jenkins
    volumes:
      - "./_jenkins:/var/jenkins_home"
    restart: always
networks:
    jenkins-network:
      driver: bridge
