version: '3.7'
services:
  jenkins:
    build:
      context: .
      dockerfile: "jenkins.Dockerfile"
    privileged: true
    user: root
    networks:
      - "jenkins-network"
    env_file:
      - jenkins.env
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - "./_jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
networks:
    jenkins-network:
      driver: bridge
