version: '3.7'
services:
  mssql_db:
    build:
      context: .
      dockerfile: "mssql.Dockerfile"
    container_name: "mssql_db"
    networks:
      - "mssql_db-network"
    ports:
      - "1433:1433"
    env_file:
      - sqlserver.env
    restart: always
    volumes: 
      - "./_mssql/sqldata:/home/mssql/data"
      - "./_mssql/sqllog:/home/mssql/log"
      - "./_mssql/sqlbackup:/home/mssql/backup"
networks:
    mssql_db-network:
        driver: bridge
