POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

mutation {
  createVehicle(type: "car", modelCode: "XYZ0192", brandName: "XYZ", launchDate: "2016-08-16")
  {
    id
  }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2MzI2MCwiZXhwIjoxNjQ2NTY2ODYwfQ.MgQEUagZZIUc_T1udNtSeJ28YOsZY5ZOA9HJW5bmlFk
X-REQUEST-TYPE: GraphQL

query {
    vehicle(id: 0)
    {
        id,
        type,
        modelCode
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

query {
    vehicles(count: 2, s: "q1")
    {
        id,
        type,
        modelCode
    }
}




POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: null
X-REQUEST-TYPE: GraphQL

query {
    authUser(email: "admin@mail.ru", password: "123456")
    {
        email,
        firstName,
        lastName,
        token,
    }
}



GET http://localhost:8080 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}






POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2ODM2OCwiZXhwIjoxNjQ2NTcxOTY4fQ.hcO37yH8c8sUHs2KuWptrlW6BXIltNr3t1rWuXRneR0
X-REQUEST-TYPE: GraphQL

query {
    userInfo(userId: 2)
    {
        email,
        roles
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MDAzMzUzMCwiZXhwIjoxNjUwMDM3MTMwfQ.Q1Y7EPbbnctzkd3shP-XV433R39we3AB8OsVy7H7J18
X-REQUEST-TYPE: GraphQL

query {
    userOrganisations
    {
        id,
        name,
        description,
        created,
        base64ImageLogo,
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTE3MjU2OCwiZXhwIjoxNjUxMTc2MTY4fQ.GhZUcdksU6FAyQnI9zjP1nL0q_0F_BweTza2YMZph9c
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentCategories
    {
        categroyId,
        name,
        description,
        imageUrl
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTE3MjU2OCwiZXhwIjoxNjUxMTc2MTY4fQ.GhZUcdksU6FAyQnI9zjP1nL0q_0F_BweTza2YMZph9c
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentQuestionsDataByCategory(categoryId: 2)
    {
        questionId,
        parentQuestionId,
        hasMultipleAnswers,
        questionWeight,
        answers{
            answerId,
            answer,
        },
        question,
    }
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    createEvaluationProcess(organisationId: 4, categoryId: 1)
}

//1014



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTE3NDgzMiwiZXhwIjoxNjUxMTc4NDMyfQ.QXF_GYRFbaHzz8Ag3in4_1qkAZveLsOZ46XZ9egzC5U
X-REQUEST-TYPE: GraphQL

query {
    getEvaluationProcesses(organisationId: 4)
    {
        processId,
        organisationId,
        organisationName,
        created,
        status,
        statusCode,
        userId,
        userEmail,
        categoryId,
        categoryName,
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    putAnswerToQuestion(questionId: 1, answerId: 2, processId: 1014)
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    removeAnswerFromQuestion(questionId: 1, answerId: 2, processId: 1014)
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    finalizeEvaluationForced(organisationId: 4, processId: 1014)
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    finalizeEvaluation(organisationId: 4, processId: 1014)
}


















