POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

mutation {
  createVehicle(type: "car", modelCode: "XYZ0192", brandName: "XYZ", launchDate: "2016-08-16")
  {
    id
  }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2MzI2MCwiZXhwIjoxNjQ2NTY2ODYwfQ.MgQEUagZZIUc_T1udNtSeJ28YOsZY5ZOA9HJW5bmlFk
X-REQUEST-TYPE: GraphQL

query {
    vehicle(id: 0)
    {
        id,
        type,
        modelCode
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

query {
    vehicles(count: 2, s: "q1")
    {
        id,
        type,
        modelCode
    }
}




POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: null
X-REQUEST-TYPE: GraphQL

query {
    authUser(email: "admin@mail.ru", password: "12345")
    {
        email,
        token
    }
}



GET http://localhost:8080 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}






POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2ODM2OCwiZXhwIjoxNjQ2NTcxOTY4fQ.hcO37yH8c8sUHs2KuWptrlW6BXIltNr3t1rWuXRneR0
X-REQUEST-TYPE: GraphQL

query {
    userInfo(userId: 2)
    {
        email,
        roles
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU3NDg2NCwiZXhwIjoxNjQ2NTc4NDY0fQ.xImSe1X6VF0BjsCELs7V5i6qXMnPXFt6bkCvmU69mdI
X-REQUEST-TYPE: GraphQL

query {
    userOrganisations
    {
        id,
        name,
        description,
        created,
        base64ImageLogo,
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0ODk5OTA2MiwiZXhwIjoxNjQ5MDAyNjYyfQ.UWbuiocnTiDoUqpbZfK0kJFzYfHAY44dT1I-31fwH54
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentCategories
    {
        categroyId,
        name,
        description
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0OTAxNTY0NCwiZXhwIjoxNjQ5MDE5MjQ0fQ.5buMjpbd5eo5F9QhbooToK7qIqsw0aqd4XP7zrZ5Wdw
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentQuestionsDataByCategory(categoryId: 2)
    {
        questionId,
        parentQuestionId,
        hasMultipleAnswers,
        questionWeight,
        answers{
            answerId,
            answer,
        },
        question,
    }
}

