POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

mutation {
  createVehicle(type: "car", modelCode: "XYZ0192", brandName: "XYZ", launchDate: "2016-08-16")
  {
    id
  }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2MzI2MCwiZXhwIjoxNjQ2NTY2ODYwfQ.MgQEUagZZIUc_T1udNtSeJ28YOsZY5ZOA9HJW5bmlFk
X-REQUEST-TYPE: GraphQL

query {
    vehicle(id: 0)
    {
        id,
        type,
        modelCode
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0Mjk0MjcwNSwiZXhwIjoxNjQyOTQ2MzA1fQ.X8uPyA46HKTmKkgWr2WXMMLOnpFcOl-r_fLEDrmZ92s
X-REQUEST-TYPE: GraphQL

query {
    vehicles(count: 2, s: "q1")
    {
        id,
        type,
        modelCode
    }
}




POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: null
X-REQUEST-TYPE: GraphQL

query {
    authUser(email: "admin@mail.ru", password: "123456")
    {
        email,
        firstName,
        lastName,
        token,
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: null
X-REQUEST-TYPE: GraphQL

query {
    extendToken(oldToken: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQwMjI1MSwiZXhwIjoxNjUxNDA1ODUxfQ.6Luub_OLc4hITuZ1bGVSsx-VSL8R_WKQ8uWj0cJvLUQ")
}


GET http://localhost:8080 HTTP/1.1

###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}






POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY0NjU2ODM2OCwiZXhwIjoxNjQ2NTcxOTY4fQ.hcO37yH8c8sUHs2KuWptrlW6BXIltNr3t1rWuXRneR0
X-REQUEST-TYPE: GraphQL

query {
    userInfo(userId: 2)
    {
        email,
        roles
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQ3NzI5NSwiZXhwIjoxNjUxNDgwODk1fQ.i9pYGVpfojny1jqOQWFHBVwjhpCGvl9UAdCt3pa6lJ8
X-REQUEST-TYPE: GraphQL

query {
    userOrganisations
    {
        id,
        name,
        description,
        created,
        base64ImageLogo,
    }
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTE3MjU2OCwiZXhwIjoxNjUxMTc2MTY4fQ.GhZUcdksU6FAyQnI9zjP1nL0q_0F_BweTza2YMZph9c
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentCategories
    {
        categroyId,
        name,
        description,
        imageUrl
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQ3NzI5NSwiZXhwIjoxNjUxNDgwODk1fQ.i9pYGVpfojny1jqOQWFHBVwjhpCGvl9UAdCt3pa6lJ8
X-REQUEST-TYPE: GraphQL

query {
    getSecurityAssessmentQuestionsDataByCategory(categoryId: 2)
    {
        questionId,
        parentQuestionAnswerId,
        hasMultipleAnswers,
        questionWeight,
        answers{
            answerId,
            questionAnswerId,
            answer,
        },
        question,
    }
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTM5MjMyOSwiZXhwIjoxNjUxMzk1OTI5fQ.aG_c2sZleQ-C6DF7Yz3jjK1iu8VZW0KML5IdjA7fabE
X-REQUEST-TYPE: GraphQL

mutation {
    createEvaluationProcess(organisationId: 4, categoryId: 1)
}

//1014



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQ2NzI0MSwiZXhwIjoxNjUxNDcwODQxfQ.q5v9i5VXomm4vjN5TSym9Je2npeEh-qRSiFB1OW6aTQ
X-REQUEST-TYPE: GraphQL

query {
    getEvaluationProcesses(organisationId: 4)
    {
        processId,
        organisationId,
        organisationName,
        created,
        status,
        statusCode,
        userId,
        userEmail,
        categoryId,
        categoryName,
    }
}



POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQxNjA5OSwiZXhwIjoxNjUxNDE5Njk5fQ.UJHNZqnn3PQr2U0T6-a0znhYnlAdD_h7ydA-to_KM4E
X-REQUEST-TYPE: GraphQL

mutation {
    putAnswerToQuestion(questionId: 1, answerId: 2, processId: 1014)
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    removeAnswerFromQuestion(questionId: 1, answerId: 2, processId: 1014)
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    finalizeEvaluationForced(organisationId: 4, processId: 1014)
}

POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTMxNjYwNywiZXhwIjoxNjUxMzIwMjA3fQ.XMHvkeDW3PE32Mmw9Qf-rgKBS0lywqy0buX_kguTjMw
X-REQUEST-TYPE: GraphQL

mutation {
    finalizeEvaluation(organisationId: 4, processId: 1014)
}




POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTM5MjMyOSwiZXhwIjoxNjUxMzk1OTI5fQ.aG_c2sZleQ-C6DF7Yz3jjK1iu8VZW0KML5IdjA7fabE
X-REQUEST-TYPE: GraphQL

query {
    getEvaluationsResults(organisationId: 4, categoryId: null)
    {
        processId,
        categoryId,
        created,
        answerTotalWeight,
        answerMaxWeight,
        statusCode,
    }
}





POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTM1MTc4MiwiZXhwIjoxNjUxMzU1MzgyfQ.9RfAQzdEn-U1ZqXSethYBh77wsWQ5yMQ4PU2wRnK3U4
X-REQUEST-TYPE: GraphQL

query {
    getEvaluationReport(processId: 3)
    {
        maxCategoryWeight,
        totalProcessWeight,
        items {
            questionId,
            answerId,
            question,
            answer,
            description,
        }
    }
}


POST http://localhost:8080/graphql
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiIsIlJPTEVfREVWIl0sImlhdCI6MTY1MTQ5NjgwNSwiZXhwIjoxNjUxNTAwNDA1fQ.I4P2FUPkhshwwYubw8oEIE2sUD-vG_71S9JkZN7mM6s
X-REQUEST-TYPE: GraphQL

query {
    getProcessAnsweredQuestions(processId: 5089)
    {
       questionAnswerId,
        questionId,
        answerId,
    }
}


